# Site settings
title: Applied Energistics 2
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: ""
url: "http://appliedenergistics.github.io"

github_username: AppliedEnergistics
github_ae2: Applied-Energistics-2
github_sio: SpatialIO-Compat

# Build settings
markdown: kramdown
